{
 "mode": "train",
 "dataset_params": { "data_folder": "data/",
                     "dataset_name": "CIFAR10",
                     "resolution": 32, },
 "save_params": { "output_dir": "models/",
                  "saveckp_freq": 1 },
 "dataloader_params": { "trainloader":{ "batch_size": 128,
                                        "accum_iter": 1,
                                        "num_workers": 10,
                                        "pin_memory": True,
                                        "drop_last": True},
                        "valloader": { "batch_size": 128,
                                       "accum_iter": 1,
                                       "num_workers": 10,
                                       "pin_memory": True,
                                       "drop_last": False} },
 "model_params": { "backbone_option":  'CNN'},
 "system_params": { "num_gpus": 1,
                    "gpu_ids": "0",
                    "random_seed": 0,},
 "training_params": { "train": { "num_epochs": 400,
                                 "val_freq": 1,
                                 "optimizer": { "name": 'sgd',
                                                "adamw": { "lr": 0.00001, "momentum": [ 0.9, 0.999 ] , "warmup_epochs": 2, "step_epoch": 400 },
                                                "sgd": { "lr": 0.0003, "momentum": 0.9 , "warmup_epochs": 2, "step_epoch": 400 } },
                                 "wd": 0.0001,
                                 "clip_grad": 1,
                                 "label_smoothing": 0.1,}, }, #
  # for swin models, keep_rate takes an integer representing the number of tokens left within a window, e.g., 1,2,...,6
  # for deit models, keep_rate is a float number between [0,1]

}